---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/widgets

- logo:
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Fedora-logo.svg/2048px-Fedora-logo.svg.png
- greeting:
    text_size: xl
    text: Fedora 

- resources:
    cpu: true
    memory: true
    disk: /

- datetime:
    text_size: xl
    format:
      timeStyle: short
      hourCycle: h23

- openmeteo:
    label: Numana
    latitude: 43.5114
    longitude: 13.6212
    timezone: Europe/Rome
    units: metric 
    cache: 5 # Time in minutes to cache API responses, to stay within limits

- unifi_console:
    url: https://192.168.0.1
    username: davide_dz
    password: Waport89!
